name: Build and Release Desktop (Unified)

# 🎯 触发条件：推送版本标签时触发
on:
  push:
    tags:
      - 'v*.*.*'           # 匹配 v2.7.0, v3.0.0 等正式版本
      - 'v*.*.*-beta.*'    # 匹配 v2.7.0-beta.1 等测试版本
      - 'v*.*.*-alpha.*'   # 匹配 v2.7.0-alpha.1 等内测版本

  # 🛠️ 手动触发（用于测试工作流）
  workflow_dispatch:
    inputs:
      version:
        description: '版本号 (例如: v2.7.0)'
        required: true
        type: string
      build_types:
        description: '构建类型'
        required: true
        default: 'ALL'
        type: choice
        options:
          - ALL
          - electron
          - tauri
          - electron,tauri

# 确保同一时间只运行一个构建任务
concurrency:
  group: unified-release-${{ github.ref }}
  cancel-in-progress: true

# 权限声明：允许创建 Release 和上传文件
permissions:
  contents: write  # 允许创建 Release 和上传资产

jobs:
  # ========================
  # 统一构建矩阵
  # ========================
  build:
    name: HexoHub_${{ matrix.build_type == 'electron' && 'Electron' || 'Tauri' }}_${{ matrix.os == 'windows-latest' && 'Windows' || matrix.os == 'macos-latest' && 'macOS' || 'Linux' }}_${{ github.ref_name }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        include:
          # Electron 构建
          - build_type: electron
            os: windows-latest
            node_version: '18'
            should_build: ${{ github.event.inputs.build_types == 'ALL' || github.event.inputs.build_types == 'electron' || github.event.inputs.build_types == 'electron,tauri' || github.event_name == 'push' }}
          - build_type: electron
            os: ubuntu-latest
            node_version: '18'
            should_build: ${{ github.event.inputs.build_types == 'ALL' || github.event.inputs.build_types == 'electron' || github.event.inputs.build_types == 'electron,tauri' || github.event_name == 'push' }}
          # Tauri 构建
          - build_type: tauri
            os: windows-latest
            node_version: '20'
            rust_target: x86_64-pc-windows-msvc
            should_build: ${{ github.event.inputs.build_types == 'ALL' || github.event.inputs.build_types == 'tauri' || github.event.inputs.build_types == 'electron,tauri' || github.event_name == 'push' }}
          - build_type: tauri
            os: macos-latest
            node_version: '20'
            rust_target: x86_64-apple-darwin
            should_build: ${{ github.event.inputs.build_types == 'ALL' || github.event.inputs.build_types == 'tauri' || github.event.inputs.build_types == 'electron,tauri' || github.event_name == 'push' }}
          - build_type: tauri
            os: ubuntu-latest
            node_version: '20'
            rust_target: x86_64-unknown-linux-gnu
            should_build: ${{ github.event.inputs.build_types == 'ALL' || github.event.inputs.build_types == 'tauri' || github.event.inputs.build_types == 'electron,tauri' || github.event_name == 'push' }}
    
    steps:
      - name: 检查是否应该构建
        if: matrix.should_build != 'true'
        run: |
          echo "跳过构建：${{ matrix.build_type }} 不在选定的构建类型中"
          exit 1

      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'npm'

      # Tauri 专用步骤
      - name: 设置 Rust 工具链
        if: matrix.build_type == 'tauri'
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy
          targets: ${{ matrix.rust_target }}

      - name: 配置 Rust 缓存
        if: matrix.build_type == 'tauri'
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri -> target

      # Linux Tauri 专用步骤
      - name: 安装系统依赖
        if: matrix.build_type == 'tauri' && matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev

      # Electron 专用步骤
      - name: 配置 Electron 缓存
        if: matrix.build_type == 'electron'
        run: |
          if [ "$RUNNER_OS" = "Windows" ]; then
            echo "ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder" >> $env:GITHUB_ENV
          else
            echo "ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder" >> $GITHUB_ENV
          fi

      - name: 安装依赖
        run: npm ci

      - name: 构建前端
        run: npm run build

      # Electron 构建步骤
      - name: 构建 Electron 应用
        if: matrix.build_type == 'electron'
        run: |
          if [ "$RUNNER_OS" = "Windows" ]; then
            npm run make -- --win --publish always
          else
            npm run make -- --linux --publish always
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Tauri 构建步骤
      - name: 构建 Tauri 应用
        if: matrix.build_type == 'tauri'
        run: npm run tauri:build
        env:
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}

      # 上传构建产物
      - name: 上传 Electron 构建产物
        if: matrix.build_type == 'electron'
        uses: actions/upload-artifact@v4
        with:
          name: electron-${{ matrix.os }}-build
          path: |
            dist/
            *.log

      - name: 上传 Tauri 构建产物
        if: matrix.build_type == 'tauri'
        uses: actions/upload-artifact@v4
        with:
          name: tauri-${{ matrix.os }}-build
          path: |
            ${{ matrix.os == 'windows-latest' && 'src-tauri/target/release/bundle/nsis/*.exe' || '' }}
            ${{ matrix.os == 'windows-latest' && 'src-tauri/target/release/bundle/msi/*.msi' || '' }}
            ${{ matrix.os == 'macos-latest' && 'src-tauri/target/release/bundle/dmg/*.dmg' || '' }}
            ${{ matrix.os == 'macos-latest' && 'src-tauri/target/release/bundle/macos/*.app' || '' }}
            ${{ matrix.os == 'ubuntu-latest' && 'src-tauri/target/release/bundle/appimage/*.AppImage' || '' }}
            ${{ matrix.os == 'ubuntu-latest' && 'src-tauri/target/release/bundle/deb/*.deb' || '' }}

      # 发布到 GitHub Releases
      - name: 发布 Electron 到 GitHub Releases
        if: matrix.build_type == 'electron'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/**/*.exe
            dist/**/*.AppImage
            dist/**/*.deb
            dist/**/*.rpm
          draft: false
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 发布 Tauri 到 GitHub Releases
        if: matrix.build_type == 'tauri'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ matrix.os == 'windows-latest' && 'src-tauri/target/release/bundle/nsis/*.exe' || '' }}
            ${{ matrix.os == 'windows-latest' && 'src-tauri/target/release/bundle/msi/*.msi' || '' }}
            ${{ matrix.os == 'macos-latest' && 'src-tauri/target/release/bundle/dmg/*.dmg' || '' }}
            ${{ matrix.os == 'ubuntu-latest' && 'src-tauri/target/release/bundle/appimage/*.AppImage' || '' }}
            ${{ matrix.os == 'ubuntu-latest' && 'src-tauri/target/release/bundle/deb/*.deb' || '' }}
          draft: false
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
